apiVersion: apps/v1
kind: Deployment
metadata:
  name: hzk-example
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hzk-example
  template:
    metadata:
      labels:
        app: hzk-example
    spec:
      containers:
        - name: hzk-example
          image: ghcr.io/net-moor/hzk-example:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5701
            - containerPort: 8080